{application,host,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{host_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[host,host_app,host_sup,install,lib_host,
                        orchistrate_host]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
